name: recibo
description: "Recibo de Aluguel Online"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  validatorless: ^1.2.3
  flutter_native_splash: ^2.4.0
  pdf: ^3.10.8
  universal_html: ^2.2.4
  signals_flutter: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
